using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class FoggyBarrierTrigger : MonoBehaviour
{

    public SceneFader sceneFader;
    public string levelToLoad;
    public bool isTransitioning = false;
    public LevelTimer levelTimer;

    void OnTriggerEnter(Collider other) {

        if (other.CompareTag("Player") && !isTransitioning) {
            Debug.Log("Player entered the trigger");
            isTransitioning = true;

            if(levelTimer != null) {

                levelTimer.StopTimer(); // This will stop the level timer for the leaderboard

            }

            PlayerPrefs.SetString("NextScene", levelToLoad); // This is used for the loading screen transitions

            if (sceneFader != null) {

                Debug.Log("sceneFader is assigned."); // This and the following debug log were generated by ChatGPT to help me find an issue
                sceneFader.FadeToScene("LoadScene");

            } else {

                Debug.LogError("sceneFader is NOT assigned!");

            }
        }
    } 
}
